<div class="slider">
    <div class="wrap__slider owl-carousel owl-theme">
        <div class="slider__item">
            <div class="slider__text">
                <p>Laptop Macbook Apple MC968ZP/A-Core i5</p>
                <p>lorem sad hfej jfnde ekfe fensaq jrf kfiw rue fnnv oierjn wndf dshe</p>
            </div>
            <div class="slider__images">
                <p><img src="{{media url=&quot;wysiwyg/slider/slide.jpg&quot;}}" alt=""></p>
            </div>
        </div>
        <div class="slider__item">
            <div class="slider__text">
                <p>Laptop Macbook Apple MC968ZP/A-Core i5</p>
                <p>lorem sad hfej jfnde ekfe fensaq jrf kfiw rue fnnv oierjn wndf dshe</p>
            </div>
            <div class="slider__images">
                <p><img src="{{media url=&quot;wysiwyg/slider/anh2.jpg&quot;}}" alt=""></p>
            </div>
        </div>
    </div>
</div>
<div class="banner flex">
    <div class="banner__item">
        <p><img src="{{media url=&quot;wysiwyg/banner/itemtop_2.jpg&quot;}}" alt=""></p>
        <div class="banner__text">
            <div class="banner__tittle">SONY VAIO SVF14217SGB-Black-(Touch)Win8</div>
            <p>Vestibulum id ligula porta felis euismod semper porta.</p>
            <div class="btn__banner"><a href="#">SHOP NOW</a></div>
        </div>
    </div>
    <div class="banner__item">
        <p><img src="{{media url=&quot;wysiwyg/banner/itemtop_1.jpg&quot;}}" alt=""></p>
        <div class="banner__text">
            <div class="banner__tittle">SONY VAIO SVF14217SGB-Black-(Touch)Win8</div>
            <p>Vestibulum id ligula porta felis euismod semper porta.</p>
            <div class="btn__banner"><a href="#">SHOP NOW</a></div>
        </div>
    </div>
    <div class="banner__item">
        <p><img src="{{media url=&quot;wysiwyg/banner/itemtop.jpg&quot;}}" alt=""></p>
        <div class="banner__text">
            <div class="banner__tittle">SONY VAIO SVF14217SGB-Black-(Touch)Win8</div>
            <p>Vestibulum id ligula porta felis euismod semper porta.</p>
            <div class="btn__banner"><a href="#">SHOP NOW</a></div>
        </div>
    </div>
</div>
<p>{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" title="NEW PRODUCTS" show_pager="0" products_count="4" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`43`^]^]"}}</p>
<p>&nbsp;</p>
<p>{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" title="FEATURES PRODUCTS" show_pager="1" products_per_page="4" products_count="4" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`44`^]^]" page_var_name="pdhxjt"}}</p>
<p>&nbsp;</p>