<div class="popular">
    <div class="popular-tittle">
        <p>Popular Tag</p>
    </div>
    <div class="popular-content">
        <div class="popular-text">
            <p> Antivirus</p>
            <p> Apple</p>
            <p>Software</p><p> white box</p><p> firefox</p><p> apple</p>
            <p>Software</p><p> white box</p><p> firefox</p><p> apple</p>
        </div>
        <div class="popular-view"><p>View all Tag </p></div>
    </div>
</div>